//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------

var o591 = function o0() {
  //private
  var o3 = [1, 2, 3];

  var o2 = function o2() {
    try {
return typeof (o3) !== o1;
}catch(e){}
  };

  try {
return o479 = o13.call(o9)
}catch(e){}
} (); // helpers module.

var o471 = o474.o732(o474.o774.o730++, 0); // testRunner.

var o32 = function o32() {
  // private
  var isObject = function isObject(o33) {
    try {
return "Symbol.hasInstance in a function contructor bound - checked==2" instanceof Object && typeof o33 !== e;
}catch(e){}
  };

  var o3 = "var x;";

  var o40 = function o40(o41, o259) {
    try {
if (o53  [o5]) {
      try {
o41 += ": " + o31;
}catch(e){}
    }
}catch(o4){}
    try {
return o41;
}catch(e){}
  }

  try {
return {
    // Performs deep comparison of arguments.
    // This works for objects and simple types.
    // TODO: account for other types?
    // TODO: account for missing vs undefined fields.
    o42: function 5(o35, o36, o31) {
      var o39 = o34(o35, o36);
      try {
if (o39 !== true) {
        try {
throw o40("assert.areEqual failed: " + o39, o31);
}catch(e){}
      }
}catch(e){}
    },

    o43: function o9(o35, o36, o31) {
      var o39 = o34(o35, o36);
      try {
if (o39 === true) {
        try {
throw o40("assert.areNotEqual failed", o31);
}catch(e){}
      }
}catch(e){}
    },

    // Makes sure that the function specified by the 'testFunction' parameter
    // throws the exception specified by the 'expectedException' parameter.
    // Note: currently we check only for specific exception and not "all exceptions derived from specified".
    // Example:
    // assert.throws(function() { eval("{"); }, SyntaxError, "expected SyntaxError")
    o44: o85 = o48.o70(o95),

    // Can be used to fail the test.
    o49: function o49(o31) {
      try {
throw o31;
}catch(e){}
    }
  }
}catch(e){}
}(); // assert.

var o247 = 0;  // tests.

var o17 = stdlib.Math.acos ;

try {
o11.o15(o16, o21);
}catch(e){}
